export enum Action {
  HORDE_MPLUS = 'horde',
  ALLIANCE_MPLUS = 'alliance',
  ACCEPT = 'accept',
  DENY = 'deny',
  CLOSE_CHANNEL = 'close-channel',
  COMPLETE = 'complete',
  CANCEL = 'cancel',
  REPOST = 'repost',
  SIGNUP = 'signup',
  TANK = 'tank',
  HEALER = 'healer',
  DPS = 'dps',
  TEAM_TAKE = 'teamtake',
  COLLECTOR = 'collector',
  KEYHOLDER = 'keyholder',
}
